name: battery_optimization
description: Battery optimization status checker for Android devices
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
